### ISSUE TITLE
(언젠가 여유가된다면) 이유 확인

### ISSUE THREAD

**Issue by jc01rho** [jc01rho-openpilot-BoltEV2019-KoKr/openpilot#22]
161cc8ea4ae08ccd200f64b0cda04a45cb9ad277

commIssue를 강제로 주석처리했는데 이게 정말 아무 영향이 없는지...

**Comment by neokii** [comment]
https://github.com/jc01rho-openpilot-BoltEV2019-KoKr/openpilot/blob/161cc8ea4ae08ccd200f64b0cda04a45cb9ad277/selfdrive/controls/controlsd.py#L59-L61

저기에서 SubMaster로 지정된 것들 중 하나 이상이 죽었거나 퍼블리싱을 하지 않으면 commIssue 경고가 발생합니다.
볼트의 경우 longitudinalPlan, radarState 는 없어도 되겠고.. 상대적으로 덜 중요한 driverCameraState 같은 거도 없어도 무방하겠지만..
modelV2, lateralPlan, roadCameraState 같이 중요한게 문제가 생기면 심각한 상태가 될 수도 있습니다.
그때 운전자가 인지하는게 중요하다 생각됩니다.

고로 commIssue 경고는 빼지 않는게 좋을 듯 합니다 ^^

**Comment by jc01rho** [comment]
@neokii 메시지 감사드립니다. 내용확인이나 반영은 수요일 이후에 가능할것같습니다. 살펴보겠습니다 :)

**Comment by jc01rho** [comment]
최근 gm차량 라이다의 15hz 이슈(?)가 해결되면서 같이 원복된 내용같습니다 감사합니다!
