### ISSUE TITLE
0.88 빌드 오류

### ISSUE THREAD

**Issue by sunsoftup** [jc01rho-openpilot-BoltEV2019-KoKr/openpilot#29]
안녕하세요~ 덕분에 항상 잘 쓰고 있습니다. 

다름이 아니라 최근에 088버전 업데이트로 인해서 빌드 오류가 발생하는 것 같습니다~ 

확인 한번 부탁드립니다. 감사합니다.

**Comment by jc01rho** [comment]
안녕하세요 답이 늦었습니다. 혹시 현재도 그러신가요?
